name: kiet_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # State management
  flutter_hooks: ^0.21.2
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1

  # UI & Animations
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  lottie: ^3.3.1
  flutter_svg: ^2.2.0
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.2

  # Responsive & Navigation
  responsive_framework: ^1.5.1
  go_router: ^15.2.0
  scroll_to_index: ^3.0.1

  # Utils
  url_launcher: ^6.3.1
  emailjs: ^4.0.0

  # Data Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  flutter_gen: ^5.10.0
  visibility_detector: ^0.4.0+2
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900