name: kiet_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.5.2 
  # Add animations to widgets

  flutter_hooks: ^0.21.2 
  # State management with hooks

  go_router: ^15.2.0 
  # App navigation and routing

  google_fonts: ^6.2.1 
  # Use Google Fonts

  lottie: ^3.3.1 
  # Play Lottie animations

  responsive_framework: ^1.5.1 
  # Make app responsive

  rive: ^0.13.20 
  # Interactive animations

  url_launcher: ^6.3.1 
  # Open links and URLs

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0 
  # Code quality rules
  
flutter:
  uses-material-design: true